### PR TITLE
copyright file in packages not correct #11: vpn-admin-portal

### PR DESCRIPTION
**Pull request by joostvb-gh**
upstream files are licensed using AGPL-3.0.  Reflect this in d/copyright (and
quote full AGPL-3.0 text there).

### CODE REVIEW

**Comment by joostvb-gh** [comment]
ready for merging afaik.

**Comment by ghost** [comment]
Looks good! Did you also check all the other packages? Or just the vpn-* packages?

**Comment by joostvb-gh** [comment]
On Tue, Oct 30, 2018 at 01:30:55AM -0700, François Kooman wrote:
> Looks good! Did you also check all the other packages? Or just the vpn-*
> packages? 

Just the vpn-* ones since that's what was the issue about.  If you
have reasons to believe other packages suffer from similar problems,
please do open another issue.  OK?

Thanks, Bye,

Joost

**Comment by ghost** [comment]
> Just the vpn-* ones since that's what was the issue about.

No it wasn't it was just an example of where it was wrong. The point of the issue was to fix it everywhere :)

**Comment by joostvb-gh** [comment]
On Tue, Oct 30, 2018 at 01:55:54AM -0700, François Kooman wrote:
> > Just the vpn-* ones since that's what was the issue about.
> 
> No it wasn't it was just an example of where it was wrong. The point of the
> issue was to fix it everywhere :)

OK, that clarifies.  I'll investigate.

**Pull request merged**
