### PR TITLE
debian/control: add php-symfony-phpunit-bridge to Build-Depends, sinc…

### PR DESCRIPTION
**Pull request by joostvb-gh**
…e we need /usr/share/php/Symfony/Bridge/PhpUnit/autoload.php in our override_dh_auto_test.

### CODE REVIEW

**Comment by ghost** [comment]
I think this is actually a bug in the Debian package as part of Debian.

**Comment by joostvb-gh** [comment]
you mean a bug in php-symfony-phpunit-bridge (2.8.7+dfsg-1.3+deb9u1) ?  could you describe the bug?

**Comment by ghost** [comment]
The software does not depend on php-symfony-phpunit-bridge, but I think php-twig (part of Debian) does. So the dependency is actually missing in php-twig! The fix would be to add the dependency to php-twig, the workaround is to add it to the vpn-admin-portal package...

Or am I missing something? The same would have to be true for vpn-user-portal by the way... and possibly php-saml-ds.

**Comment by ghost** [comment]
Okay, it has nothing to do with Twig? But with phpunit? Maybe phpunit is broken then... not sure whta is going on here.

**Comment by ghost** [comment]
this was resolved afaik.

**Pull request closed without merging**
